#!/usr/bin/env python3
"""Surgically patch English text baked into illustration PNGs with French text.

These illustrations were generated by an AI image model; the painted artwork
(scenes, icons, characters) cannot be regenerated here, but the English labels
sit on flat-color bands/cartouches distinct from the artwork. This module
covers those flat regions with their background color and redraws the
replacement text in the same place/style, leaving the artwork untouched.
"""

from PIL import Image, ImageDraw, ImageFont

REGULAR_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
BOLD_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


def find_font(size, bold=False):
    return ImageFont.truetype(BOLD_FONT_PATH if bold else REGULAR_FONT_PATH, size)


def sample_fill_color(img, bbox, inset=3):
    """Average the four corners just outside the text (inside bbox edges) to get
    the surrounding flat background color."""
    rgb = img.convert("RGB")
    px = rgb.load()
    x0, y0, x1, y1 = bbox
    w, h = rgb.size
    pts = [
        (x0 + inset, y0 + inset),
        (x1 - 1 - inset, y0 + inset),
        (x0 + inset, y1 - 1 - inset),
        (x1 - 1 - inset, y1 - 1 - inset),
    ]
    samples = [px[max(0, min(x, w - 1)), max(0, min(y, h - 1))] for x, y in pts]
    r = sum(s[0] for s in samples) // len(samples)
    g = sum(s[1] for s in samples) // len(samples)
    b = sum(s[2] for s in samples) // len(samples)
    return (r, g, b)


def fit_font(draw, text, max_width, start_size, bold=False, min_size=10):
    """Return the largest font size (<= start_size) at which every line of
    `text` fits within max_width, down to min_size."""
    size = start_size
    while size > min_size:
        font = find_font(size, bold=bold)
        widest = max(draw.textbbox((0, 0), line, font=font)[2] for line in text.split("\n"))
        if widest <= max_width:
            return font
        size -= 1
    return find_font(min_size, bold=bold)


def patch_region(img, bbox, text, font, text_color, fill_color=None, align="left", line_spacing=1.2):
    """Cover bbox with fill_color (auto-sampled if omitted) then draw `text`
    (may contain \\n for multiple lines), vertically centered in bbox and
    horizontally aligned per `align` ('left'|'center'|'right')."""
    draw = ImageDraw.Draw(img)
    if fill_color is None:
        fill_color = sample_fill_color(img, bbox)
    draw.rectangle(bbox, fill=fill_color)

    x0, y0, x1, y1 = bbox
    lines = text.split("\n")
    line_metrics = []
    for line in lines:
        b = draw.textbbox((0, 0), line, font=font)
        line_metrics.append((line, b[2] - b[0], b[3] - b[1]))

    line_h = max(h for _, _, h in line_metrics) * line_spacing
    total_h = line_h * len(lines)
    y = y0 + ((y1 - y0) - total_h) / 2

    for line, w, _ in line_metrics:
        if align == "center":
            x = x0 + ((x1 - x0) - w) / 2
        elif align == "right":
            x = x1 - w
        else:
            x = x0
        draw.text((x, y), line, font=font, fill=text_color)
        y += line_h

    return img


def patch_and_save(path, patches, out_path=None):
    """patches: list of dicts with keys bbox, text, font, text_color, and
    optionally fill_color/align. Applies them in order and saves to out_path
    (defaults to overwriting `path`)."""
    img = Image.open(path).convert("RGB")
    for p in patches:
        patch_region(
            img,
            p["bbox"],
            p["text"],
            p["font"],
            p["text_color"],
            fill_color=p.get("fill_color"),
            align=p.get("align", "left"),
            line_spacing=p.get("line_spacing", 1.2),
        )
    img.save(out_path or path)
    return out_path or path
